manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: r0ckl0bsta
      revision: main
      import: app/west.yml
  self:
    path: config
